project-info:
  name: myProject
  version: v1
  description : Local


system:
  propertySources:
    expose-enabled: ture #스프링 스타트시 시스템 property를 로그로 보여줄지 설정


server:
  port: 8080
  servlet.session:
    timeout: 60m
    cookie:
      name: JSESSIONID
      http-only: true
      secure: true
      same-site: none
  #사설 인증사의 경우 로컬 테스트를 위해 브라우저 설정 필요 (chrome://flags/ -> Allow invalid certificates for resources loaded from localhost. -> Enabled, 도메인은 front.localhost:8080 형태로 구성)
  ssl:
    key-store: classpath:keystore/keystore.p12
    key-store-type: PKCS12
    key-store-password: keystore_password

  error: #스프링에서 제공하는 에러 기본 처리 설정
    include-exception: true #exception 정보를 보여줄지
    include-stacktrace: always #stacktrace 를 보여줄지
    path: error #에러 처리에 대한 뷰 경로
    whitelabel.enabled: false #스프링의 기본 에러 페이지(Whitelabel Error Page)를 사용할지


Storage:
  multipartFiles:
    basePath: c:/


logging:
  level: #log level은 logback config 파일에 그대로 반영됨
    root: info
    com:
      sptek.webfw: debug
      zaxxer.hikari.pool.HikariPool: info
    org:
      mybatis.spring: info
    jdbc:
      audit: info
      resultset: info
      resultsettable: debug #INFO  #SQL 결과 데이터 Table을 로그로 남긴다.
      sqlonly: info     #SQL만 로그로 남긴다.
      sqltiming: info    #SQL과 소요시간을 표기한다.
      connection: info  # 커넥션 확인가능
  config: classpath:logbackConfig/logback-spring-local.xml


spring:
  web:
    resources:
      static-locations:
        - classpath:/resources/
        - classpath:/static/
        
  devtools: #코드 수정 실시간 반영
    livereload:
      enabled: true
    restart:
      enabled: true
  config:
    import: #기본 프로퍼티가 아닌 추가적인 property 파일로 구성 필요시.
      - classpath:specificProperties/specificName.yml
      - classpath:specificProperties/secureOption.yml
  thymeleaf:
    enabled: true
    cache: false
    check-template-location: true
    #prefix: classpath:/templates/thymeleaf/ #이렇게 설정하면 로컬서버에서 실행중 실시간 수정 변경이 안되는 현상이 있음
    prefix: file:src/main/resources/templates/thymeleaf/
    suffix: .html
  #jsp로 설정할때
  #mvc:
  #  view:
  #    prefix: /WEB-INF/views/
  #    suffix: .jsp
  h2: #H2 임베드 DB 사용은 프로퍼티설정만 있음
    console:
      enabled: true #웹콘솔 사용 여부
      path: /h2-console #웹콘솔 url 경로, ex:https://localhost:8080/h2-console/
  datasource: #리플리카 구성이 아닌 단순 DS 사용
    url: jdbc:h2:mem:local #메모리모드, 휘발성, @Entity 클레스에 대해 자동으로 TB 구성, schema.sql, data.sql 자동 실행
    #url: jdbc:h2:G:\내 드라이브\work\sptek\frameWork\webfw1\spt-wfw\src\main\resources\h2\local;AUTO_SERVER=TRUE  #서버모드(파일), 해당 위치에 cmd로 copy con local.mv.db 을 통해 초기 DB 파일 생성, 서버모드로
    driverClassName: org.h2.Driver
    username: sa
    password:


#PageInoSupport 클레스 관련 설정
pagehelper:
  helper-dialect: mysql
  auto-dialect: true
  page-size-zero: false
  reasonable: true
  offset-as-page-num: false
  row-bounds-with-count: false
  auto-runtime-dialect: false
  close-conn: true
  default-count: true


jasypt:
  encryptor:
    bean=encryptorBean: jasyptStringEncryptor
    secretKey: JasyptStringEncryptor_key_Hello


# Swagger springdoc-ui Configuration
springdoc:
  packages-to-scan: com.sptek.webfw.example.api.api1
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    path: swagger-ui.html         # Swagger UI 경로 => https://localhost:8080/swagger-ui.html
    tags-sorter: alpha            # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
    operations-sorter: alpha      # alpha: 알파벳 순 태그 정렬, method: HTTP Method 순 정렬
  api-docs:
    path: /api-docs/json
    groups:
      enabled: true
  cache:
    disabled: true